# Generated by Django 3.2.5 on 2021-07-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='type',
            field=models.CharField(choices=[('notice', '공지'), ('dsum', '디썸')], max_length=10, null=True),
        ),
    ]
